//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetDataNetFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            this.SurveyorAssignmentRoles = new HashSet<SurveyorAssignmentRole>();
        }
    
        public long Idx { get; set; }
        public long ActivityID { get; set; }
        public System.DateTime Created { get; set; }
        public long RowVersion { get; set; }
        public string ScopeOfEOs { get; set; }
        public Nullable<bool> EmailSent { get; set; }
        public Nullable<System.DateTime> EmailSentDate { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Assignment Assignment1 { get; set; }
        public virtual Assignment Assignment2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyorAssignmentRole> SurveyorAssignmentRoles { get; set; }
    }
}
